spring:
  datasource:
    url: jdbc:mysql://111.230.102.73:3306/test?characterEncoding=utf8&useSSL=true
    username: peison
    password: 123456

mybatis:
  config-location: classpath:mybatis-config.xml